import Head from "next/head";
import Header from "@/components/Header";
import { Container, Content } from "@/styles/styles";
import Card from "@/components/Cards";
import Footer from "@/components/Footer";
import { useEffect, useState } from "react";
import api from "@/service/api";

interface ProductsProps {
    id: number;
    name: string;
    brand: string;
    description: string;
    photo: string;
    price: string;
    createdAt: Date;
    updatedAt: Date;
}

export default function Home() {
    const [products, setProducts] = useState<ProductsProps[]>([]);

    async function getProducts() {
        api.get("/products", {
            params: {
                page: 1,
                rows: 8,
                sortBy: "id",
                orderBy: "DESC",
            },
        }).then((response) => setProducts(response.data.products));
        console.log(products);
    }

    useEffect(() => {
        getProducts();
    }, []);

    return (
        <Container>
            <Head>
                <title>Mks Frontend Challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <Header />
            <Content>
                {products.map((item) => (
                    <Card
                        key={item.id}
                        title={item.name}
                        description={item.description}
                        image={item.photo}
                        price={`R$${item.price}`}
                    />
                ))}
            </Content>
            <Footer />
        </Container>
    );
}
